{
 "title": "Avail Mainnret : Validator 01",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Basic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15)/count(count(node_cpu_seconds_total) by (cpu)) * 100  "
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Build Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds-node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes  )",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Best Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalize Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Sync LAG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Finalized Sync LAG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Block Proposal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_proposal_time_bucket{le=\"+Inf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "__auto" }
   ]
  },
  { "title": "Avail Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sync Best",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Sync LAG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Finalized Sync LAG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "time taken to construct a block and prepare it for proposal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(le) (substrate_proposer_block_proposal_time_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time taken to construct new block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(le) (substrate_proposer_block_constructed_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "6h Change: time taken to construct a block and prepare it for proposal",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (changes(substrate_proposer_block_proposal_time_bucket[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "6h Change: time taken to construct new block",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (changes(substrate_proposer_block_constructed_bucket[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of transactions included in block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The reason why the block proposing was ended",
   "type": "timeseries",
   "description": "This doesn't include errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by(reason) (substrate_proposer_end_proposal_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of GRANDPA prevotes cast locally",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_prevotes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of GRANDPA precommits cast locally",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_precommits_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total[1m]) - rate(substrate_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Peers count"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_requested",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "substrate_sync_peers" }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "substrate_database_cache_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "substrate_state_cache_bytes" }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "substrate_sync_queued_blocks" }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "substrate_number_leaves" }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total[1m]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"iowait\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Busy iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=~\".*irq\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{ mode=\"idle\"}[1m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes  )",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_avail_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum by(device) (rate(node_disk_io_now[1m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "targets": [
    {
     "expr": "sum by(device) (rate(node_disk_read_time_seconds_total[1m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "targets": [
    {
     "expr": "sum by(device) (rate(node_disk_write_time_seconds_total[1m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(device) (irate(node_network_receive_bytes_total[1m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(device) (irate(node_network_transmit_bytes_total[1m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}